### ISSUE TITLE
Total Boron Parameterization: Kuliński et al. (2018)

### ISSUE THREAD

**Issue by d-sandborn** [mvdh7/PyCO2SYS#60]
A paper by [Honkanen et al. (2021)](https://os.copernicus.org/articles/17/1657/2021/) used a total boron parameterization by [Kuliński et al. (2018)](https://www.sciencedirect.com/science/article/pii/S0304420318300252).  Is this implemented in PyCO2SYS?  If not, is there interest in implementing it?  This option may make the program more useful to researchers in brackish waters and/or the Baltic Sea.

**Comment by mvdh7** [comment]
It's not, but sure this would be a good thing to add!

To do (you're welcome to do this or if not then I should eventually get around to it):

- [ ] Add `pyco2.salts.borate_kulinski` function [here](https://github.com/mvdh7/PyCO2SYS/blob/main/PyCO2SYS/salts.py), with the same format as the other two `borate_` functions
- [ ] Add extra `np.where` line to the end of `pyco2.salts._co2sys_TB` to use `borate_kulinski` when `WhoseTB==3` 
- [ ] Add a brief description to the docs [here](https://github.com/mvdh7/PyCO2SYS/blob/main/docs/co2sys_nd.md)
- [ ] Add the reference to the docs [here](https://github.com/mvdh7/PyCO2SYS/blob/main/docs/refs.md)
- [ ] If there is some check value in the Kulinski paper, then add a test to confirm the function works (in a new file [here](https://github.com/mvdh7/PyCO2SYS/tree/main/tests))

**Comment by d-sandborn** [comment]
Thanks for the To Do's.  I'll see if I can make some progress on them.

**Comment by mvdh7** [comment]
Thanks @d-sandborn - now incorporated into v1.8.1 (released yesterday)!
