### ISSUE TITLE
conda release?

### ISSUE THREAD

**Issue by uliw** [mvdh7/PyCO2SYS#69]
I am building a package that depends on some  pyCO2sys routines. I would like to release this package via conda. However, that will only work if all dependencies (including pyCO2sys)  can be satisfied by the conda package manager.  

I see that adding pyCO2sys to conda has been attempted before: https://github.com/conda-forge/staged-recipes/pull/21796

But apparently never succeeded.  A quick check suggests that all of pyCO2sys's requirements exist on conda, so this should be straightforward unless there is OS-dependent code somewhere.

Are there plans to try this again? Also, I am happy to help with this.

**Comment by mvdh7** [comment]
There will be a new release of PyCO2SYS within the next few weeks and within that I have already (hopefully) fixed the issues that caused problems with the previous attempt.

So the intention is to add it to conda-forge very soon.

Thanks for the offer for help, I will reach out if I am still struggling!

**Comment by mvdh7** [comment]
Hi @uliw, PyCO2SYS is now [available on conda-forge](https://anaconda.org/conda-forge/pyco2sys)

**Comment by uliw** [comment]
Thanks!
