### ISSUE TITLE
[Extension] Dependency setting of pyco2sys onto itself in pyproject.toml using poetry

### ISSUE THREAD

**Issue by pfheiter** [mvdh7/PyCO2SYS#72]
Hej all,

first of all: thanks for sharing this awesome python adaption of the CO2SYS! During my work, I encounterd a small issue when trying to install the python package via poetry (https://python-poetry.org/) which is nowadays very popular to manage python packages for a project. Instead of calling pip install manually, we can configure inside the pyporject.toml the package dependencies.

Doing so led to the following problem:
<img width="435" alt="grafik" src="https://github.com/user-attachments/assets/11f49c1e-9cff-40f1-b6e0-f086302533ce" />

I noticed, that in the package setting, the dependency are set to itself which is cyclic then. 
<img width="642" alt="grafik" src="https://github.com/user-attachments/assets/5fe972b2-f477-485e-a2df-e4d1acda5782" />

So in order to support poetry, we might remove the cyclic dependency definition in the pyproject.toml. So my question: 

What was the reason to list the package itself in the dependency field?

Best
Pascal

**Comment by mvdh7** [comment]
Hi @pfheiter, thanks for pointing this out! The self-dependency is a hangover from earlier versions when I was less competent... I am working on a new major version where it will be removed, but that's still weeks/months away from being released. For now, I can release a patch on the current version without this, hopefully in the next day or two.

**Comment by mvdh7** [comment]
... in fact, this is now already resolved with v1.8.3.4 :)

**Comment by pfheiter** [comment]
Wow, that was a very quick response! Thanks a lot :) I can confirm that it's working now. Maybe it would also make sense to organize the package which you use in the pyproject.toml?

Here is the example of how to use ur package though 
<img width="642" alt="grafik" src="https://github.com/user-attachments/assets/58aa66ad-9770-4fc1-b42f-b2633af8e123" />
